config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  scope "(:locale)", locale: /es|en/ do

  resources :broker_accounts
  resources :azzets
  resources :trades
  resources :settings
  resources :dashboard
  resources :statistics
  resources :feedbacks
  resources :tools
  resources :webtrader
  resources :types
  resources :market_sessions
  resources :strategies
  resources :account_balances
  resources :brokers

  root 'ruteador#index'
  get 'home' => 'welcome#index', as: :welcome
  get '/dashboard' => 'dashboard#index', as: :home

  post 'dashboard/:id/update_result' => 'dashboard#update_result', as: :update_result
  post 'dashboard/create' => 'dashboard#create', as: :create_dashboard
  delete 'dashboard/:id/destroy' => 'dashboard#destroy', as: :destroy_dashboard 
  get 'dashboard/trades_data/:id' => 'dashboard#trades_data', as: :trades_data
  get 'dashboard/today_data/:id' => 'dashboard#today_data'

  get 'webtrader/index'
  post 'webtrader/:id/update' => 'webtrader#update', as: :update_webtrader
  post 'webtrader/create' => 'webtrader#create', as: :create_webtrader
  delete 'webtrader/:id/destroy' => 'webtrader#destroy', as: :destroy_webtrader
  get 'webtrader/trades_data/:id' => 'webtrader#trades_data'
  get 'webtrader/today_data/:id' => 'webtrader#today_data'

  get 'broker_accounts/:id/current_balance' => 'broker_accounts#current_balance', as: :current_balance

  get 'strategies/:id/total_trades' => 'strategies#total_trades', as: :strategies_total_trades
  get 'azzets/:id/total_trades' => 'azzets#total_trades', as: :azzets_total_trades

  get 'settings/:id/user_settings' => 'settings#user_settings', as: :user_settings
  
  get 'statistics/trades_chart/:id' => 'statistics#trades_chart'
  get 'statistics/strategies_chart/:id' => 'statistics#strategies_chart'
  get 'statistics/azzets_chart/:id' => 'statistics#azzets_chart'
  get 'statistics/index'

end
end

app/models/azzet.rb
class Azzet < ActiveRecord::Base
	attr_accessible :Type, :Name

  def self.get_azzets

  	azzets = Azzet.order(:Name)

  end
end

app/controllers/azzets_controller.rb
class AzzetsController < ApplicationController
  before_action :authenticate_admin!,:except => [:total_trades]
  before_action :set_azzet, only: [:show, :edit, :update, :destroy, :total_trades]

  respond_to :html

  def index
    @azzets = Azzet.all
    respond_with(@azzets)
  end

  def show
    respond_with(@azzet)
  end

  def new
    @azzet = Azzet.new
    respond_with(@azzet)
  end

  def edit
  end

  def create
    @azzet = Azzet.new(azzet_params)

    respond_to do |format|
      if @azzet.save
        format.html { redirect_to '/azzets' }
        format.json { render :show, status: :ok, location: @azzet }
      else
        format.html { render :edit }
        format.json { render json: @azzet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @azzet.update(azzet_params)
        format.html { redirect_to '/azzets' }
        format.json { render :show, status: :ok, location: @azzet }
      else
        format.html { render :edit }
        format.json { render json: @azzet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @azzet.destroy
    respond_with(@azzet)
  end

  def total_trades
    respond_to do |format|
       format.json do 
        render :json => Trade.total_trades_by_azzet(params[:id], current_user.id)
      end
     end
  end

  private
    def set_azzet
      @azzet = Azzet.find(params[:id])
    end

    def azzet_params
      params.require(:azzet).permit(:Type, :Name)
    end
end

app/helpers/azzets_helper.rb
module AzzetsHelper
end

app/views/azzets/_form.html.erb
<%= form_for(@azzet, :html => {:class => 'form-horizontal', :role => 'form'}) do |f| %>

  <div class="panel-body">

    <% if @azzet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@azzet.errors.count, "error") %> prohibited this azzet from being saved:</h2>

        <ul>
        <% @azzet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :Type %><br>
      <%= f.hidden_field :Type %>
      <%= select_tag(:Type, options_for_select([["Currencies", "Currencies"], ["Commodities", "Commodities"], ["Indices", "Indices"], ["Stock", "Stock"]], selected: :option), :name => "azzet[Type]", class:'form-control')%>
    </div>
    <div class="field">
      <%= f.label :Name %><br>
      <%= f.text_field :Name, :class=> "form-control" %>
    </div>

  </div>
  <div class="panel-footer text-right">
      <%= link_to 'Back', azzets_path, :class=> "btn btn-default" %>
      <%= f.submit "Save", :class=> "btn btn-info" %>
  </div>
<% end %>

app/views/azzets/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel">
    	<div class="panel-heading">
    		<h3 class="panel-title">Editing Azzet
    		</h3>
    	</div>
		<%= render 'form' %>
    </div>
  </div>
</div>

app/views/azzets/index.html.erb
<script src="/assets/bootstrap-select.min.js"></script>

<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-lg-12">
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-control"></div>
                <h3 class="panel-title">Listing Assets</h3>
            </div>
            <div class="panel-body">
                <div class="pad-btm form-inline">
                    <div class="col-sm-6 table-toolbar-left">
                         <%= link_to new_azzet_path do %>
                          <button class="btn btn-purple btn-labeled fa fa-plus">Nuevo Asset</button>
                        <% end %>                  
                    </div>
                </div>
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                      <thead>
                        <tr>
                          <th>Type</th>
                          <th>Name</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>

                      <tbody>
                        <% @azzets.each do |azzet| %>
                          <tr>
                            <td><%= azzet.Type %></td>
                            <td><%= azzet.Name %></td>
                            <td><%= link_to 'Show', azzet %></td>
                            <td><%= link_to 'Edit', edit_azzet_path(azzet) %></td>
                            <td><%= link_to 'Destroy', azzet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
      $('#dataTables-example').DataTable();
  });
</script>

app/views/azzets/new.html.erb
<h1>New Azzet</h1>

<%= render 'form' %>

<%= link_to 'Back', azzets_path %>

app/views/azzets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @azzet.Type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @azzet.Name %>
</p>

<%= link_to 'Edit', edit_azzet_path(@azzet) %> |
<%= link_to 'Back', azzets_path %>