config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  scope "(:locale)", locale: /es|en/ do

  resources :broker_accounts
  resources :azzets
  resources :trades
  resources :settings
  resources :dashboard
  resources :statistics
  resources :feedbacks
  resources :tools
  resources :webtrader
  resources :types
  resources :market_sessions
  resources :strategies
  resources :account_balances
  resources :brokers

  root 'ruteador#index'
  get 'home' => 'welcome#index', as: :welcome
  get '/dashboard' => 'dashboard#index', as: :home

  post 'dashboard/:id/update_result' => 'dashboard#update_result', as: :update_result
  post 'dashboard/create' => 'dashboard#create', as: :create_dashboard
  delete 'dashboard/:id/destroy' => 'dashboard#destroy', as: :destroy_dashboard 
  get 'dashboard/trades_data/:id' => 'dashboard#trades_data', as: :trades_data
  get 'dashboard/today_data/:id' => 'dashboard#today_data'

  get 'webtrader/index'
  post 'webtrader/:id/update' => 'webtrader#update', as: :update_webtrader
  post 'webtrader/create' => 'webtrader#create', as: :create_webtrader
  delete 'webtrader/:id/destroy' => 'webtrader#destroy', as: :destroy_webtrader
  get 'webtrader/trades_data/:id' => 'webtrader#trades_data'
  get 'webtrader/today_data/:id' => 'webtrader#today_data'

  get 'broker_accounts/:id/current_balance' => 'broker_accounts#current_balance', as: :current_balance

  get 'strategies/:id/total_trades' => 'strategies#total_trades', as: :strategies_total_trades
  get 'azzets/:id/total_trades' => 'azzets#total_trades', as: :azzets_total_trades

  get 'settings/:id/user_settings' => 'settings#user_settings', as: :user_settings
  
  get 'statistics/trades_chart/:id' => 'statistics#trades_chart'
  get 'statistics/strategies_chart/:id' => 'statistics#strategies_chart'
  get 'statistics/azzets_chart/:id' => 'statistics#azzets_chart'
  get 'statistics/index'

end
end

app/controllers/webtrader_controller.rb
class WebtraderController < ApplicationController
  include DashboardHelper
  before_action :authenticate_user!
  before_action :all_trades, only: [:index, :create, :update, :destroy]
  before_action :set_trades, only: [:edit, :update, :destroy]
  respond_to :html, :json

  def index
  end

  def new
    @brokerAccount = BrokerAccount.user_brokerAccounts(current_user.id)

    @strategy = Strategy.user_strategies(current_user.id)

    @azzets = Azzet.get_azzets

    @trade = Trade.new
  end

  def create
    @trade = Trade.create(trade_params)
  end

  def update

    @trade.Result = params[:Result]

    if(params[:Result] == 'WON')
      @trade.Payout = ((Float(@trade.Amount) * Float(@trade.OnProfit)) / 100)
    elsif (params[:Result] == 'TIE') 
      @trade.Payout = 0
    else
      @trade.Payout = 0 - Float(@trade.Amount) + (Float(@trade.Amount) * Float(@trade.OnLoss)) / 100
    end
    
    @trade.save

    @account = BrokerAccount.find(@trade.BrokerAccount_id)
    @account.Balance = Float(@account.Balance) + Float(@trade.Payout)
    @account.save

  end

  def destroy
    @trade.destroy
  end

  def today_data
    
    respond_to do |format|
        format.json do 
          render :json => day_full_data(Time.zone.today)
        end
      end
  end

  private

    def all_trades
      @trades = Trade.open_trades(current_user.id).order(:id)
    end

    def set_trades
      @trade = Trade.find(params[:id])
    end

    def trade_params
      params.require(:trade).permit(:User_id, :BrokerAccount_id, :Strategy_id, :Azzet_id, :Option, :Amount, :OnProfit, :OnLoss, :Payout, :Result, :UseMartingale, :UseCompoundInterest, :Position)
    end
end

app/helpers/webtrader_helper.rb
module WebtraderHelper
end

app/views/webtrader/_charts.html.erb
<!-- TradingView Widget BEGIN -->
<script type="text/javascript" src="https://d33t3vvu2t2yu5.cloudfront.net/tv.js"></script>
<script type="text/javascript">
new TradingView.widget({
  "autosize": true,
  "symbol": "EURUSD",
  "interval": "5",
  "timezone": "Etc/UTC",
  "theme": "White",
  "style": "1",
  "locale": "en",
  "toolbar_bg": "#f1f3f6",
  "hide_side_toolbar": false,
  "allow_symbol_change": true,
  "hotlist": false,
  "calendar": false,
  "studies": [
    "RSI@tv-basicstudies",
    "StochasticRSI@tv-basicstudies",
    "MASimple@tv-basicstudies"
  ],
  "show_popup_button": true,
  "popup_width": "1000",
  "popup_height": "650"
});
</script>
<!-- TradingView Widget END -->

app/views/webtrader/_current_trades.html.erb
<div class="table-responsive">
    <table id="tbl_open_trades" class="table table-striped table-hover">
        <thead>
            <tr>
                <th><%= I18n.t('dashboard_trades_time') %></th>
                <th><%= I18n.t('dashboard_trades_azzet') %></th>
                <th><%= I18n.t('dashboard_trades_amount') %></th>
                <th class="text-center"><%= I18n.t('dashboard_trades_actions') %></th>
            </tr>
        </thead>
        <tbody>
            <% @trades.each do |trade| %>
                <tr>
                    <td>
                        <%= trade.created_at.strftime("%H:%M") %>
                    </td>
                    <td>
                        <%= trade.Azzet.Name %>
                    </td>
                    <td>
                        $<%= trade.Amount %>
                    </td>
                    <td class="text-center">
                        <div class="btn-group">
                            <a href="#" class="btn btn-xs btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="glyphicon glyphicon-ok"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                <li>
                                    <%= link_to 'WON', update_webtrader_path(:trade => trade, :id => trade.id, :Result => 'WON' ), :method => :post, :remote => true %>
                                </li>
                                <li>
                                    <%= link_to 'TIE', update_webtrader_path(:trade => trade, :id => trade.id, :Result => 'TIE' ), :method => :post, :remote => true %>
                                </li>
                                <li>
                                    <%= link_to 'LOST', update_webtrader_path(:trade => trade, :id => trade.id, :Result => 'LOST' ), :method => :post, :remote => true %>
                                </li>           
                            </ul>  
                        </div>
                        <%= link_to destroy_webtrader_path(:id => trade.id), :method => :delete, data: { confirm: I18n.t('dashboard_alert_delete') }, :remote => true, :class => 'btn btn-xs btn-danger add-tooltip' do %>
                            <i class="fa fa-times"></i>
                        <% end %>  
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/webtrader/_form.html.erb
<script type="text/javascript" src="/assets/jquery-select/bootstrap-select.min.js"></script>
<script type="text/javascript" src="/assets/jquery-validate/jquery.validate.min.js"></script>
<script type="text/javascript" src="/assets/jquery-validate/jquery-validate.bootstrap-tooltip.min.js"></script>
<script type="text/javascript" src="/assets/cookies.js"></script>
<style type="text/css">
  .form-horizontal .form-group{margin-bottom: 5px!important;}
</style>
<%= form_for(@trade, remote: true, :url => create_webtrader_path, :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>

  <div class="panel">
    <div class="panel-body">

        <% if @trade.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this setting from being saved:</h2>

          <ul>
          <% @trade.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.hidden_field :User_id, :value => current_user.id %>

      <div class="form-group">
          <%= f.label I18n.t('dashboard_broker_account'), class:'col-xs-3 col-sm-3 col-md-3' %>
          <div class="col-xs-9 col-sm-9 col-md-9">
            <%= f.collection_select(:BrokerAccount_id, @brokerAccount, :id, :name, {},  {class: "form-control selectpicker", :name => "trade[BrokerAccount_id]", :onchange => 'get_balance(this.value)', :data => {:validation => "required"} } ) %>
          </div>
      </div>

      <div class="form-group">
          <%= f.label I18n.t('dashboard_strategy'), class:'col-xs-3 col-sm-3 col-md-3' %>
          <div class="col-xs-9 col-sm-9 col-md-9">
            <%= f.collection_select(:Strategy_id, @strategy, :id, :Name , {}, {class: "form-control selectpicker", :name => "trade[Strategy_id]", :onchange => 'get_strategy_success_rate(this.value)', :data => {:validation => "required"}}) %>
          </div>  
      </div>

      <div class="form-group">
          <%= f.label I18n.t('dashboard_azzet'), class:'col-xs-3 col-sm-3 col-md-3' %>
          <div class="col-xs-9 col-sm-9 col-md-9">
             <%= f.collection_select(:Azzet_id, @azzets, :id, :Name , {title: I18n.t('dashboard_select_azzet')}, {class: "form-control selectpicker", :name => "trade[Azzet_id]", :onchange => 'get_azzet_success_rate(this.value)', :data => {:validation => "required", "live-search" => "true", :size => "10"}}) %>
          </div>
      </div>

      <div class="form-group ">
          <div class='col-xs-3 col-sm-3 col-md-3' style="padding-right:0;">
            <%= f.label I18n.t('dashboard_amount') %>
            <a href="#" onclick="javascript:get_recommended_amount();" class="btn btn-xs btn-default" alt="Sugerir monto">
              <i class="fa fa-pencil"></i>
            </a>
          </div>
          <div class="col-xs-9 col-sm-9 col-md-9">
            <div class="input-group">
              <div class="input-group-addon label-default">
                $
              </div>
              <%= f.number_field :Amount, class:'form-control', type:'number', :onchange => 'calcule_percent()' %>
              <div class="input-group-addon label-default">
                <small>
                  <span id="lbl_percent_suggested"></span>
                </small>
              </div>
            </div>       
          </div>
      </div>

      <div class="form-group">
          <%= f.label I18n.t('dashboard_onprofit'), class:'col-xs-3 col-sm-3 col-md-3' %>
          <div class="col-xs-9 col-sm-9 col-md-9">
            <div class="input-group">
              <div class="input-group-addon label-default">
                %
              </div>
              <%= f.number_field :OnProfit, class:'form-control', type:'number', :onchange => 'calcule_onprofit()' %>
              <div class="input-group-addon label-default">
                <small>
                  <span id="lbl_onprofit_payout"></span>
                </small>
              </div>
            </div>
          </div>      
      </div>

      <div class="form-group">
          <%= f.label I18n.t('dashboard_onloss'), class:'col-xs-3 col-sm-3 col-md-3' %>
          <div class="col-xs-9 col-sm-9 col-md-9">
            <div class="input-group">
               <div class="input-group-addon label-default">
                %
              </div>
              <%= f.number_field :OnLoss, class:'form-control', type:'number', :onchange => 'calcule_onlost()' %>
              <div class="input-group-addon label-default">
                <small>
                  <span id="lbl_onlost_payout"></span>
                </small>
              </div>
            </div>
          </div>
      </div>


      <%= f.hidden_field :Payout, :value => '' %>
      <%= f.hidden_field :Result, :value => '' %>
      <%= f.hidden_field :UseMartingale, :value => 'false' %>
      <%= f.hidden_field :UseCompoundInterest, :value => 'false' %>
    </div>
    <div class="panel-footer text-right">
        <button type="button" class="btn btn-default" onclick="javascript:$('#trade-form').slideUp(350);$('#content-tabs').slideDown(350);"><%= I18n.t('dashboard_button_close') %></button>
        <%= f.submit I18n.t('dashboard_button_create'), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
      
<script type="text/javascript">
  var account_balance = 0;
  var maximum_percent_per_trade = 0;

  $.ajax({
    type: "GET",
    url: "/settings/1/user_settings",
    success: function(data){

      maximum_percent_per_trade = data[0] != null ? data[0].MaximumPercentPerTrade : 0;
    }
  });

  $("form").validate({
    rules: {
      'trade[BrokerAccount_id]': {required: true},
      'trade[Amount]': {required: true, number: true},
      'trade[OnProfit]': {required: true, number: true},
      'trade[OnLoss]': {required: true, number: true}
    },
    tooltip_options: {
      'trade[Amount]': {placement:'botton',html:true},
      'trade[OnProfit]': {placement:'botton',html:true},
      'trade[OnLoss]': {placement:'botton',html:true}
    }
  });

  $('.selectpicker').selectpicker({});

  inicialize_form();


  function inicialize_form()
  {
    selected_account = getCookie("selected_account");
    if(selected_account != "")
    {
      $("#trade_BrokerAccount_id").val(selected_account);
      $("#trade_BrokerAccount_id").change();
    }

    selected_strategy = getCookie("selected_strategy");
    if(selected_strategy != "")
    {
      $("#trade_Strategy_id").val(selected_strategy);
      $("#trade_Strategy_id").change();
    }

    selected_azzet = getCookie("selected_azzet");
    if(selected_azzet != "")
    {
      $("#trade_Azzet_id").val(selected_azzet);
      $("#trade_Azzet_id").change();
    }

    selected_amount = getCookie("selected_amount");
    if(selected_amount != "")
    {
      $("#trade_Amount").val(selected_amount);
    }
    else
    {
      get_recommended_amount();
    }

    selected_onprofit = getCookie("selected_onprofit");
    if(selected_onprofit != "")
    {
      $("#trade_OnProfit").val(selected_onprofit);
    }
    else
    {
      $("#trade_OnProfit").val("70");
    }

    selected_onloss = getCookie("selected_onloss");
    if(selected_onloss != "")
    {
      $("#trade_OnLoss").val(selected_onloss);
    }
    else
    {
      $("#trade_OnLoss").val("0");
    }


    calcule_percent();
  }

  function get_balance (accountId) {

    //set cookie
    setCookie("selected_account", accountId, 1);

    $.ajax({
      type: "GET",
      url: "/broker_accounts/" + accountId + "/current_balance",
      success: function(data){

        if(data != null)
        {
          account_balance = (data).toFixed(2);
          $("#lbl_account_balance").text("$ " + account_balance);
          get_recommended_amount();
        }
        else
        {
          $("#lbl_account_balance").text("Debe ingresar el saldo de la cuenta");
        }
      }
    });
  }

  function get_recommended_amount(){
    //Calcular la cantidad a invertir sugerida
    amount_suggested = Math.round((maximum_percent_per_trade * account_balance) / 100);
    $("#trade_Amount").val(amount_suggested);
    $("#lbl_percent_suggested").text(maximum_percent_per_trade + " %");

    calcule_onprofit();
    calcule_onlost();
  }

  function get_strategy_success_rate(strategyId) {

    //set cookie
    setCookie("selected_strategy", strategyId, 1);

    $.ajax({
      type: "GET",
      url: "/strategies/" + strategyId + "/total_trades",
      success: function(data){

        if(data.length > 0)
        {
          won = tie = lost = 0;

          $.each(data, function (i, item) {
            if (item.Result === 'WON') {
              won = item.total_trades;
            }
            else if (item.Result === 'TIE') {
              tie = item.total_trades;
            }
            else if (item.Result === 'LOST') {
              lost = item.total_trades;
            }
          });

          total_trades = won + tie + lost;
          success_rate = Math.round(((won + tie) / total_trades) * 100);
          
          $("#lbl_strategy_rate").text(success_rate + " %");
        }
        else
        {
          $("#lbl_strategy_rate").text("N/A"); 
        }
      }
    });
  }

  function get_azzet_success_rate(azzetId) {
    
    //set cookie
    setCookie("selected_azzet", azzetId, 1);

    $.ajax({
      type: "GET",
      url: "/azzets/" + azzetId + "/total_trades",
      success: function(data){

        if(data.length > 0)
        {
          won = data[2] != null ? data[2].total_trades : 0;
          tie = data[1] != null ? data[1].total_trades : 0;
          lost = data[0] != null ? data[0].total_trades : 0;
          total_trades = won + tie + lost;
          success_rate = Math.round(((won + tie) / total_trades) * 100);

          $("#lbl_azzet_rate").text(success_rate + " %");
        }
        else
        {
          $("#lbl_azzet_rate").text("N/A"); 
        }
      }
    });
  }

  function calcule_percent(){
    if(account_balance!=""){
      amount = $("#trade_Amount").val();
      percent = Math.round((amount / account_balance) * 100);
      
      $("#lbl_percent_suggested").text(percent + " %");

      //set cookie
      setCookie("selected_amount", amount, 1);

      calcule_onprofit();
      calcule_onlost();
    }
    else
    {
      setTimeout(function() {calcule_percent();}, 1000);
    }
  }

  function calcule_onprofit(){
      amount = $("#trade_Amount").val();
      onprofit = $("#trade_OnProfit").val();

      if(amount != "" && onprofit != ""){
        profit = ((amount * onprofit) / 100).toFixed(2);
           
        //$("#lbl_onprofit_payout").text("$" + (parseFloat(amount) + parseFloat(profit)) + " ($" + profit +")");
        $("#lbl_onprofit_payout").text("$" + (parseFloat(amount) + parseFloat(profit)).toFixed(2));

        //set cookie
        setCookie("selected_onprofit", onprofit, 1);
      }
  }

  function calcule_onlost(){
      amount = $("#trade_Amount").val();
      onloss = $("#trade_OnLoss").val();

      if(amount != "" && onloss != ""){
        profit = ((amount * onloss) / 100).toFixed(2);

        $("#lbl_onlost_payout").text("$" + (parseFloat(profit) - parseFloat(amount)).toFixed(2));
        //$("#lbl_onlost_payout").text("$" + profit + " ($" + (parseFloat(profit) - parseFloat(amount)) +")");

        //set cookie
        setCookie("selected_onloss", onloss, 1);
      }
  }
</script>

app/views/webtrader/create.js.erb
$('#trades').html("<%= escape_javascript(render 'current_trades') %>");
$('#trade-form').slideUp(350);
$('#content-tabs').slideDown(350);

app/views/webtrader/destroy.js.erb
$('#trades').html("<%= escape_javascript(render 'current_trades') %>");

app/views/webtrader/new.js.erb
$('#trade-form').html("<%= j (render 'form') %>");
$('#trade-form').slideDown(350);
$('#content-tabs').slideUp(350);

app/views/webtrader/update.js.erb
$('#trades').html("<%= escape_javascript(render 'current_trades') %>");
update_charts();