config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  scope "(:locale)", locale: /es|en/ do

  resources :broker_accounts
  resources :azzets
  resources :trades
  resources :settings
  resources :dashboard
  resources :statistics
  resources :feedbacks
  resources :tools
  resources :webtrader
  resources :types
  resources :market_sessions
  resources :strategies
  resources :account_balances
  resources :brokers

  root 'ruteador#index'
  get 'home' => 'welcome#index', as: :welcome
  get '/dashboard' => 'dashboard#index', as: :home

  post 'dashboard/:id/update_result' => 'dashboard#update_result', as: :update_result
  post 'dashboard/create' => 'dashboard#create', as: :create_dashboard
  delete 'dashboard/:id/destroy' => 'dashboard#destroy', as: :destroy_dashboard 
  get 'dashboard/trades_data/:id' => 'dashboard#trades_data', as: :trades_data
  get 'dashboard/today_data/:id' => 'dashboard#today_data'

  get 'webtrader/index'
  post 'webtrader/:id/update' => 'webtrader#update', as: :update_webtrader
  post 'webtrader/create' => 'webtrader#create', as: :create_webtrader
  delete 'webtrader/:id/destroy' => 'webtrader#destroy', as: :destroy_webtrader
  get 'webtrader/trades_data/:id' => 'webtrader#trades_data'
  get 'webtrader/today_data/:id' => 'webtrader#today_data'

  get 'broker_accounts/:id/current_balance' => 'broker_accounts#current_balance', as: :current_balance

  get 'strategies/:id/total_trades' => 'strategies#total_trades', as: :strategies_total_trades
  get 'azzets/:id/total_trades' => 'azzets#total_trades', as: :azzets_total_trades

  get 'settings/:id/user_settings' => 'settings#user_settings', as: :user_settings
  
  get 'statistics/trades_chart/:id' => 'statistics#trades_chart'
  get 'statistics/strategies_chart/:id' => 'statistics#strategies_chart'
  get 'statistics/azzets_chart/:id' => 'statistics#azzets_chart'
  get 'statistics/index'

end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	belongs_to :user

	attr_accessible :title, :description, :user_id
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_admin!,:except => [:new, :create]
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        #ModelMailer.new_record_notification(@feedback).deliver

        format.html { redirect_to :controller => "/dashboard", notice: 'feedback' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:title, :description, :user_id)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback, :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>
  
  	<div class="panel-body">

	  <% if @feedback.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

	      <ul>
	      <% @feedback.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <%= f.hidden_field :user_id, :value => current_user.id %>

	  <h4><%= I18n.t('feedback_form_message_h2')%></h4>
	  <br>

	  <div class="form-group">
	      <%= f.label I18n.t('feedback_form_title'), class:'col-sm-3' %>
	      <div class="col-sm-9">
	        <%= f.text_field :title, class:'form-control', :data => {:validation => "required"} %>
	      </div>
	  </div>

	  <div class="form-group">
	      <%= f.label I18n.t('feedback_form_description'), class:'col-sm-3' %>
	      <div class="col-sm-9">
	        <%= f.text_area :description, cols:'20', rows:'10', class:'form-control', :data => {:validation => "required"} %>
	      </div>
	  </div>
	</div>
	<div class="panel-footer text-right">
		<%= link_to :controller=> '/dashboard' do %>
            <span  class="btn btn-default">
                <%= I18n.t('feedback_form_cancel') %>
            </span>
        <% end %>
	  	<%= f.submit I18n.t('feedback_form_send'), :class=> "btn btn-info" %>
	</div>

<% end %>

<script>
  $.validate();
</script>

app/views/feedbacks/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= I18n.t('feedback_title_edit') %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-body">

		<%= render 'form' %>

      </div>
    </div>
  </div>
</div>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.title %></td>
        <td><%= feedback.description %></td>
        <td><%= feedback.user_id %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel">
    	<div class="panel-heading">
    		<h3 class="panel-title"><%= I18n.t('feedback_form_message_h1')%>
    		</h3>
    	</div>
		<%= render 'form' %>
    </div>
  </div>
</div>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feedback.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feedback.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>