config/routes.rb
Rails.application.routes.draw do

  resources :feedbacks
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  scope "(:locale)", locale: /es|en/ do

  resources :broker_accounts
  resources :azzets
  resources :trades
  resources :settings
  resources :dashboard
  resources :statistics
  resources :feedbacks
  resources :tools
  resources :webtrader
  resources :types
  resources :market_sessions
  resources :strategies
  resources :account_balances
  resources :brokers

  root 'ruteador#index'
  get 'home' => 'welcome#index', as: :welcome
  get '/dashboard' => 'dashboard#index', as: :home

  post 'dashboard/:id/update_result' => 'dashboard#update_result', as: :update_result
  post 'dashboard/create' => 'dashboard#create', as: :create_dashboard
  delete 'dashboard/:id/destroy' => 'dashboard#destroy', as: :destroy_dashboard 
  get 'dashboard/trades_data/:id' => 'dashboard#trades_data', as: :trades_data
  get 'dashboard/today_data/:id' => 'dashboard#today_data'

  get 'webtrader/index'
  post 'webtrader/:id/update' => 'webtrader#update', as: :update_webtrader
  post 'webtrader/create' => 'webtrader#create', as: :create_webtrader
  delete 'webtrader/:id/destroy' => 'webtrader#destroy', as: :destroy_webtrader
  get 'webtrader/trades_data/:id' => 'webtrader#trades_data'
  get 'webtrader/today_data/:id' => 'webtrader#today_data'

  get 'broker_accounts/:id/current_balance' => 'broker_accounts#current_balance', as: :current_balance

  get 'strategies/:id/total_trades' => 'strategies#total_trades', as: :strategies_total_trades
  get 'azzets/:id/total_trades' => 'azzets#total_trades', as: :azzets_total_trades

  get 'settings/:id/user_settings' => 'settings#user_settings', as: :user_settings
  
  get 'statistics/trades_chart/:id' => 'statistics#trades_chart'
  get 'statistics/strategies_chart/:id' => 'statistics#strategies_chart'
  get 'statistics/azzets_chart/:id' => 'statistics#azzets_chart'
  get 'statistics/index'

end
end

app/models/strategy.rb
class Strategy < ActiveRecord::Base
  attr_accessible :Name, :Type, :User_id
  belongs_to :User

  def self.user_strategies(userId)

  	strategies = where(:User_id => userId).order(:Name)

  end


end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_strategy, only: [:show, :edit, :update, :destroy, :total_trades]

  # GET /strategies
  # GET /strategies.json
  def index
    @strategies = Strategy.user_strategies(current_user.id)
  end

  # GET /strategies/1
  # GET /strategies/1.json
  def show
  end

  # GET /strategies/new
  def new
    @strategy = Strategy.new
  end

  # GET /strategies/1/edit
  def edit
  end

  # POST /strategies
  # POST /strategies.json
  def create
    @strategy = Strategy.new(strategy_params)

    respond_to do |format|
      if @strategy.save
        format.html { redirect_to '/strategies' }
        format.json { render :show, status: :created, location: @strategy }
      else
        format.html { render :new }
        format.json { render json: @strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strategies/1
  # PATCH/PUT /strategies/1.json
  def update
    respond_to do |format|
      if @strategy.update(strategy_params)
        format.html { redirect_to '/strategies' }
        format.json { render :show, status: :ok, location: @strategy }
      else
        format.html { render :edit }
        format.json { render json: @strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strategies/1
  # DELETE /strategies/1.json
  def destroy

    Trade.where(:Strategy_id => @strategy.id).destroy_all

    @strategy.destroy
    respond_to do |format|
      format.html { redirect_to strategies_url, notice: 'Strategy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def total_trades
    respond_to do |format|
       format.json do 
        render :json => Trade.total_trades_by_strategy(params[:id], current_user.id)
      end
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strategy
      @strategy = Strategy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def strategy_params
      params.require(:strategy).permit(:Name, :Type, :User_id)
    end
end

app/helpers/strategies_helper.rb
module StrategiesHelper
	def strategy_chart_data_filter(start, date_end , account, strategy, asset )
		#Rails.logger.info "current_user #{current_user.inspect}"
		win_by_day   = Trade.where(:User_id => 1).where(result:  "WIN").count
		tie_by_day   = Trade.where(:User_id => current_user.id).where(result:  "TIE").trades_grouped_by_date_filter_strategy(start,date_end)
		lost_by_day  = Trade.where(:User_id => current_user.id).where(result: "LOST").trades_grouped_by_date_filter_strategy(start,date_end)
		strategy     = Strategy.where(id: Trade.where(:User_id => current_user.id)).pluck(:Name)
		Rails.logger.info "Nombre Estrategia #{win_by_day}"

			(strategy).map do |estrategia|
				{	
					 created_at: "#{estrategia}",
					 total_win:  win_by_day  || 0,
					 total_tie:  tie_by_day.try(:first).try(:total)  || 0,
					 total_lost: lost_by_day.try(:first).try(:total)  || 0, 
				}

		end
	end	
end

app/views/strategies/_form.html.erb
<script type="text/javascript" src="/assets/jquery-validate/jquery.validate.min.js"></script>
<script type="text/javascript" src="/assets/jquery-validate/jquery-validate.bootstrap-tooltip.min.js"></script>
<%= form_for(@strategy, :html => {:class => 'form-horizontal', :role => 'form'} ) do |f| %>

  <div class="panel-body">

    <% if @strategy.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@strategy.errors.count, "error") %> prohibited this strategy from being saved:</h2>

        <ul>
        <% @strategy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :User_id, :value => current_user.id %>

    <div class="form-group">
        <%= f.label I18n.t('strategies_table_name'), class:'col-sm-3' %>
        <div class="col-sm-9">
          <%= f.text_field :Name, class:'form-control' %>
        </div>
    </div>

    <%= f.hidden_field :Type, :value => "Private" %>
  </div>

  <div class="panel-footer text-right">
      <%= link_to 'Back', strategies_path, :class=> "btn btn-default" %>
      <%= f.submit I18n.t('strategies_button_save'), :class=> "btn btn-info" %>
  </div>

<% end %>

<script>
  $("form").validate({
    rules: {
      'strategy[Name]': {required: true}
    },
    tooltip_options: {
      'strategy[Name]': {placement:'top',html:true}
    }
  });
</script>

app/views/strategies/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title"><%= I18n.t('strategies_title_edit') %>
        </h3>
      </div>
    <%= render 'form' %>
    </div>
  </div>
</div>

app/views/strategies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-lg-12">
        <div class="panel">
            <div class="panel-heading">
              <h3 class="panel-title"><%= I18n.t('strategies_title') %>
              </h3>
            </div>
            <div class="panel-body">
              <div class="dataTable_wrapper">
                  <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                      <tr>
                        <th><%= I18n.t('strategies_table_name') %></th>
                        <th colspan="2"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @strategies.each do |strategy| %>
                        <tr class="odd gradeX">
                          <td><%= strategy.Name %></td>
                          <td><%= link_to I18n.t('strategies_button_edit'), edit_strategy_path(strategy) %></td>
                          <td><%= link_to I18n.t('strategies_button_destroy'), strategy, method: :delete, data: { confirm: I18n.t('dashboard_alert_delete') } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
            <div class="panel-footer text-right">
              <%= link_to I18n.t('strategies_button_new'), new_strategy_path, :class => "btn btn-info" %>
            </div>
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<br>

app/views/strategies/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title"><%= I18n.t('strategies_title_new') %>
        </h3>
      </div>
    <%= render 'form' %>
    </div>
  </div>
</div>

app/views/strategies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @strategy.Name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @strategy.Type %>
</p>

<p>
  <strong>User:</strong>
  <%= @strategy.User %>
</p>

<%= link_to 'Edit', edit_strategy_path(@strategy) %> |
<%= link_to 'Back', strategies_path %>